/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import screenScene from '../assets/3d/screen.glb'

const Screen = (props) => {
    const screenRef = useRef()

    const { nodes, materials } = useGLTF(screenScene)

    return (
        <a.group ref={screenRef}{...props} >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Screen_1.geometry}
                material={nodes.Screen_1.material}
                position={[0, -0.06, 0.298]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.497, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Screen.geometry}
                material={nodes.Screen.material}
                position={[0, -0.06, 0.298]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.497, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2.geometry}
                material={nodes.Box_2.material}
                scale={[1.65, 1.152, 0.358]}
            />
            <group position={[0.638, -0.624, 0.322]} rotation={[0.03, 0, 0]} scale={[2.44, 1.209, 1.209]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Camera_decor.geometry}
                    material={nodes.Camera_decor.material}
                    rotation={[0.301, 0.765, 2.354]}
                />
            </group>
            <group
                position={[0.638, -0.624, 0.018]}
                rotation={[0.045, 0, 0]}
                scale={[2.44, 1.209, 1.209]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Camera_decor_2.geometry}
                    material={nodes.Camera_decor_2.material}
                    rotation={[0.286, 0.765, 2.354]}
                />
            </group>
            <group
                position={[0.332, 0.555, 0.319]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1.269, 0.782, 0.66]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Camera_decor_1.geometry}
                    material={nodes.Camera_decor_1.material}
                    rotation={[1.902, 0.765, 2.354]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tube_base_1.geometry}
                material={nodes.Tube_base_1.material}
                position={[-0.794, 0.314, 0.357]}
                rotation={[-0.005, 0.369, -3.115]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Camera.geometry}
                material={nodes.Camera.material}
                position={[0, 0.646, 0.244]}
                scale={0.307}
            />
            <group
                position={[0.451, 0.585, 0.415]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.289, 0.277, 0.245]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Camera_holder.geometry}
                    material={nodes.Camera_holder.material}
                    rotation={[0.849, 1.57, -2.294]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box.geometry}
                material={nodes.Box.material}
                position={[0, -1.484, -0.678]}
                scale={[3.777, 0.587, 2.419]}
            />
            <group
                position={[0.451, 0.585, 0.415]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.289, 0.277, 0.245]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Camera_holder_1.geometry}
                    material={nodes.Camera_holder_1.material}
                    rotation={[0.849, 1.57, -2.294]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Camera_eye.geometry}
                material={nodes.Camera_eye.material}
                position={[0, 0.643, 0.392]}
                scale={0.22}
            />
            <group
                position={[-0.744, 0.408, 0.368]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={[-0.937, 0.877, 0.682]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Tube_top.geometry}
                    material={nodes.Tube_top.material}
                    rotation={[-1.566, 0.369, -0.026]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chair.geometry}
                material={nodes.Chair.material}
                position={[-2.171, -1.524, 4.046]}
                rotation={[3.048, 1.254, -3.062]}
                scale={2.414}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chair_platform.geometry}
                material={nodes.Chair_platform.material}
                position={[-0.869, -3.247, 3.507]}
                scale={[1.861, 0.351, 1.861]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_1.geometry}
                material={nodes.Box_1.material}
                position={[-2.949, 0.126, 2.219]}
                rotation={[0, 1.563, 0]}
                scale={[3.755, 2.119, 0.348]}
            />
            <group
                position={[2.631, -1.067, 0.146]}
                rotation={[-0.162, 0.028, 1.514]}
                scale={[0.307, 0.141, 0.058]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lathe_1.geometry}
                    material={nodes.Lathe_1.material}
                    rotation={[-0.114, -0.1, -1.545]}
                />
            </group>
            <group
                position={[-2.38, -1.077, 0.047]}
                rotation={[-0.162, 0.028, 1.514]}
                scale={[0.307, 0.141, 0.058]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Lathe_2.geometry}
                    material={nodes.Lathe_2.material}
                    rotation={[-0.114, -0.1, -1.545]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box_2.geometry}
                material={nodes.Box_2.material}
                position={[-0.016, -1.028, 0.9]}
                scale={[2.22, 0.215, 1.321]}
            />
            <group
                position={[-3.04, -4.647, 4.016]}
                rotation={[0.002, -1.571, 0]}
                scale={[1.973, 1.13, 0.905]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh_3.geometry}
                    material={nodes.Mesh_3.material}
                    rotation={[-0.802, -0.248, -0.84]}
                />
            </group>
            <directionalLight
                intensity={1.668}
                decay={2}
                color="#ff0a9e"
                position={[13.418, 13.83, -4.036]}
                rotation={[-2.409, 0.544, 1.258]}
            />
            <OrthographicCamera
                makeDefault={false}
                far={34.936}
                near={0.834}
                position={[-0.071, 2.559, 21.685]}
                rotation={[-0.186, 0.374, 0.069]}
            />
            <OrthographicCamera
                makeDefault={false}
                far={34.936}
                near={0.834}
                position={[6.093, 2.559, 19.222]}
                rotation={[-0.186, 0.374, 0.069]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere.geometry}
                material={nodes.Sphere.material}
                position={[0, -5.544, 2.329]}
                scale={[18.581, 3.442, 18.581]}
            />
        </a.group>
    )
}

export default Screen
